project_id = "eddrshyqlrpxgvyxpjee"

[functions.encrypt-upload]
verify_jwt = false

[functions.decrypt-document]
verify_jwt = false

[functions.purge-expired-docs]
verify_jwt = false

[functions.translate-listing]
verify_jwt = false

[functions.wa-webhook]
verify_jwt = false

[functions.notify-whatsapp]
verify_jwt = false

[functions.og-listing]
verify_jwt = false

[functions.oglisting]
verify_jwt = false

[functions.manage-points]
verify_jwt = false

[functions.expire-addons]
verify_jwt = false

[functions.purge-search-logs]
verify_jwt = false

[functions.notify-saved-searches]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
