project_id = "eddrshyqlrpxgvyxpjee"

[functions.encrypt-upload]
verify_jwt = false

[functions.decrypt-document]
verify_jwt = false

[functions.purge-expired-docs]
verify_jwt = false

[functions.translate-listing]
verify_jwt = false

[functions.wa-webhook]
verify_jwt = false

[functions.notify-whatsapp]
verify_jwt = false

[functions.og-listing]
verify_jwt = false

[functions.oglisting]
verify_jwt = false
